AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Buckets for Clickstream ETL Pipeline'

Parameters:
  EnvironmentName:
    Description: Environment name (dev, staging, prod)
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  
  ProjectName:
    Description: Project name for bucket naming
    Type: String
    Default: clickstream-etl

Resources:
  # Bronze Layer Bucket - Raw data landing zone
  BronzeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${EnvironmentName}-bronze-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: Layer
          Value: Bronze

  # Scripts Bucket - PySpark scripts storage
  ScriptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${EnvironmentName}-scripts-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Scripts

  # Logs Bucket - EMR and Airflow logs
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${EnvironmentName}-logs-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireLogs
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Logs

  # Iceberg Warehouse Bucket - Processed data (Silver/Gold layers)
  IcebergBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${EnvironmentName}-iceberg-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: Layer
          Value: Iceberg

Outputs:
  BronzeBucketName:
    Description: Name of the Bronze layer bucket
    Value: !Ref BronzeBucket
    Export:
      Name: !Sub '${AWS::StackName}-BronzeBucket'
  
  BronzeBucketArn:
    Description: ARN of the Bronze layer bucket
    Value: !GetAtt BronzeBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BronzeBucketArn'
  
  ScriptsBucketName:
    Description: Name of the Scripts bucket
    Value: !Ref ScriptsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ScriptsBucket'
  
  LogsBucketName:
    Description: Name of the Logs bucket
    Value: !Ref LogsBucket
    Export:
      Name: !Sub '${AWS::StackName}-LogsBucket'
  
  IcebergBucketName:
    Description: Name of the Iceberg warehouse bucket
    Value: !Ref IcebergBucket
    Export:
      Name: !Sub '${AWS::StackName}-IcebergBucket'
  
  # Convenience paths for Airflow environment variables
  BronzePath:
    Description: S3 path for bronze data
    Value: !Sub 's3://${BronzeBucket}/clickstream/'
  
  EMRLogUri:
    Description: S3 URI for EMR logs
    Value: !Sub 's3://${LogsBucket}/emr-logs/'
